### ISSUE TITLE
Code Usage without Explicit Approval

### ISSUE THREAD

**Issue by L7NEG** [YimMenu-Lua/GunVan#3]
As @SilentSal0 Owns This Code and you say it is not then i advice you to remove it in The Next 5 Days Else Further Action Can Be Taken Outside Yim Menu Repo And Not Limited To UC 

![image](https://github.com/user-attachments/assets/b5ce6548-4685-455f-8831-3c0c18e5f1b3)

**Comment by inteldork** [comment]
yikes!

**Comment by L7NEG** [comment]
@yimmura this is the last warning from me here further actions i will take it on UC and not limited to other sources i work for

**Comment by L7NEG** [comment]
sine this kid started it then he will face it

**Comment by SilentSal0** [comment]
I don't know why am I involved in this conflict, but I can say few things:
1) I didn't skid any line from this script. The whole GunVan thingy in my script (Silent Night) for Kiddion's Modest Menu is written by me from scratch.
2) I don't have any troubles with skidders, who get my code into their scripts, etc.
3) I always give credits, if I implement someone's code into my script and always can delete that part if asked.
Thanks for reading, have a good time.

**Comment by L7NEG** [comment]
> Are you fucking retarded? Those coordinates come from the freemode script. Why don't we just type a seething and coping response and then close the ticket?

thats what i try to say and i have obeyd yimura but still

**Comment by L7NEG** [comment]
since the brainroted started it first then i dont want to listen him crying over rn

**Comment by gir489returns** [comment]
> > Are you fucking retarded? Those coordinates come from the freemode script. Why don't we just type a seething and coping response and then close the ticket?
> 
> thats what i try to say and i have obeyd yimura but still

![image](https://github.com/user-attachments/assets/9d781154-0ee7-4594-8475-17a6384c8caf)

You still don't have my permission to use Casino Pacino which you are still using in your script:

![image](https://github.com/user-attachments/assets/607de988-f62a-4ac3-8bf6-1c9532b3f48a)

IDK, code looks exactly the same to me, you fucking idiot.

**Comment by L7NEG** [comment]
> > > Are you fucking retarded? Those coordinates come from the freemode script. Why don't we just type a seething and coping response and then close the ticket?
> > 
> > 
> > thats what i try to say and i have obeyd yimura but still
> 
> ![image](https://private-user-images.githubusercontent.com/100792176/348838020-9d781154-0ee7-4594-8475-17a6384c8caf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzM5MTgsIm5iZiI6MTcyMTA3MzYxOCwicGF0aCI6Ii8xMDA3OTIxNzYvMzQ4ODM4MDIwLTlkNzgxMTU0LTBlZTctNDU5NC04NDc1LTE3YTYzODRjOGNhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQyMDAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTE3MjhhMGUzZmJjMTFiMDFkYjI3NDA1NmU2Nzk5YjhiYTY5YzFlYzAzMzQ2MmMxMjFlYWIyNzZiNzhiMGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-OiFkpRvnPCmjS88luKVIwtfO34V1hwQA81DDa0FA_Q)
> 
> You still don't have my permission to use Casino Pacino which you are still using in your script:
> 
> ![image](https://private-user-images.githubusercontent.com/100792176/348838391-607de988-f62a-4ac3-8bf6-1c9532b3f48a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzM5MTgsIm5iZiI6MTcyMTA3MzYxOCwicGF0aCI6Ii8xMDA3OTIxNzYvMzQ4ODM4MzkxLTYwN2RlOTg4LWY2MmEtNGFjMy04YmY2LTFjOTUzMmIzZjQ4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQyMDAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODIwODA5ZTc2M2MyYWNhZGE4NGVkMzE0NTY4MWIwYzRjYjA1NzEwYjAzMTYzOGFmODRjMTZkZTFmNGJlMDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qY4-HYvMaWWkZ6_BoYuphTOPh6upngA8R964pZaFv5M)
> 
> IDK, code looks exactly the same to me, you fucking idiot.

i removed the uselss codes only the wheel only is in you fucking brainrotted kid

**Comment by gir489returns** [comment]
> > > > Are you fucking retarded? Those coordinates come from the freemode script. Why don't we just type a seething and coping response and then close the ticket?
> > > 
> > > 
> > > thats what i try to say and i have obeyd yimura but still
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/100792176/348838020-9d781154-0ee7-4594-8475-17a6384c8caf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzM5MTgsIm5iZiI6MTcyMTA3MzYxOCwicGF0aCI6Ii8xMDA3OTIxNzYvMzQ4ODM4MDIwLTlkNzgxMTU0LTBlZTctNDU5NC04NDc1LTE3YTYzODRjOGNhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQyMDAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTE3MjhhMGUzZmJjMTFiMDFkYjI3NDA1NmU2Nzk5YjhiYTY5YzFlYzAzMzQ2MmMxMjFlYWIyNzZiNzhiMGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-OiFkpRvnPCmjS88luKVIwtfO34V1hwQA81DDa0FA_Q)
> > You still don't have my permission to use Casino Pacino which you are still using in your script:
> > ![image](https://private-user-images.githubusercontent.com/100792176/348838391-607de988-f62a-4ac3-8bf6-1c9532b3f48a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzM5MTgsIm5iZiI6MTcyMTA3MzYxOCwicGF0aCI6Ii8xMDA3OTIxNzYvMzQ4ODM4MzkxLTYwN2RlOTg4LWY2MmEtNGFjMy04YmY2LTFjOTUzMmIzZjQ4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQyMDAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODIwODA5ZTc2M2MyYWNhZGE4NGVkMzE0NTY4MWIwYzRjYjA1NzEwYjAzMTYzOGFmODRjMTZkZTFmNGJlMDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qY4-HYvMaWWkZ6_BoYuphTOPh6upngA8R964pZaFv5M)
> > IDK, code looks exactly the same to me, you fucking idiot.
> 
> i removed the uselss codes only the wheel only is in you fucking brainrotted kid

4 days left, remove the entire Casino script or get purged from the repo. Tick tock.

**Comment by L7NEG** [comment]
> > > > > Are you fucking retarded? Those coordinates come from the freemode script. Why don't we just type a seething and coping response and then close the ticket?
> > > > 
> > > > 
> > > > thats what i try to say and i have obeyd yimura but still
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/100792176/348838020-9d781154-0ee7-4594-8475-17a6384c8caf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzM5MTgsIm5iZiI6MTcyMTA3MzYxOCwicGF0aCI6Ii8xMDA3OTIxNzYvMzQ4ODM4MDIwLTlkNzgxMTU0LTBlZTctNDU5NC04NDc1LTE3YTYzODRjOGNhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQyMDAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTE3MjhhMGUzZmJjMTFiMDFkYjI3NDA1NmU2Nzk5YjhiYTY5YzFlYzAzMzQ2MmMxMjFlYWIyNzZiNzhiMGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-OiFkpRvnPCmjS88luKVIwtfO34V1hwQA81DDa0FA_Q)
> > > You still don't have my permission to use Casino Pacino which you are still using in your script:
> > > ![image](https://private-user-images.githubusercontent.com/100792176/348838391-607de988-f62a-4ac3-8bf6-1c9532b3f48a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzM5MTgsIm5iZiI6MTcyMTA3MzYxOCwicGF0aCI6Ii8xMDA3OTIxNzYvMzQ4ODM4MzkxLTYwN2RlOTg4LWY2MmEtNGFjMy04YmY2LTFjOTUzMmIzZjQ4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQyMDAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODIwODA5ZTc2M2MyYWNhZGE4NGVkMzE0NTY4MWIwYzRjYjA1NzEwYjAzMTYzOGFmODRjMTZkZTFmNGJlMDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qY4-HYvMaWWkZ6_BoYuphTOPh6upngA8R964pZaFv5M)
> > > IDK, code looks exactly the same to me, you fucking idiot.
> > 
> > 
> > i removed the uselss codes only the wheel only is in you fucking brainrotted kid
> 
> 4 days left, remove the entire Casino script or get purged from the repo. Tick tock.

tick tok i wont do it now then i will do more aggressive actions

**Comment by gir489returns** [comment]
> > > > > > Are you fucking retarded? Those coordinates come from the freemode script. Why don't we just type a seething and coping response and then close the ticket?
> > > > > 
> > > > > 
> > > > > thats what i try to say and i have obeyd yimura but still
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/100792176/348838020-9d781154-0ee7-4594-8475-17a6384c8caf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzM5MTgsIm5iZiI6MTcyMTA3MzYxOCwicGF0aCI6Ii8xMDA3OTIxNzYvMzQ4ODM4MDIwLTlkNzgxMTU0LTBlZTctNDU5NC04NDc1LTE3YTYzODRjOGNhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQyMDAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTE3MjhhMGUzZmJjMTFiMDFkYjI3NDA1NmU2Nzk5YjhiYTY5YzFlYzAzMzQ2MmMxMjFlYWIyNzZiNzhiMGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-OiFkpRvnPCmjS88luKVIwtfO34V1hwQA81DDa0FA_Q)
> > > > You still don't have my permission to use Casino Pacino which you are still using in your script:
> > > > ![image](https://private-user-images.githubusercontent.com/100792176/348838391-607de988-f62a-4ac3-8bf6-1c9532b3f48a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzM5MTgsIm5iZiI6MTcyMTA3MzYxOCwicGF0aCI6Ii8xMDA3OTIxNzYvMzQ4ODM4MzkxLTYwN2RlOTg4LWY2MmEtNGFjMy04YmY2LTFjOTUzMmIzZjQ4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQyMDAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODIwODA5ZTc2M2MyYWNhZGE4NGVkMzE0NTY4MWIwYzRjYjA1NzEwYjAzMTYzOGFmODRjMTZkZTFmNGJlMDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qY4-HYvMaWWkZ6_BoYuphTOPh6upngA8R964pZaFv5M)
> > > > IDK, code looks exactly the same to me, you fucking idiot.
> > > 
> > > 
> > > i removed the uselss codes only the wheel only is in you fucking brainrotted kid
> > 
> > 
> > 4 days left, remove the entire Casino script or get purged from the repo. Tick tock.
> 
> tick tok i wont do it now then i will do more aggressive actions

 NOT MORE AGGRESSIVE ACTIONS! I'M SO SCARED! What's he gonna do? Steal more code? WOW!

**Comment by L7NEG** [comment]
> > > > > > > Are you fucking retarded? Those coordinates come from the freemode script. Why don't we just type a seething and coping response and then close the ticket?
> > > > > > 
> > > > > > 
> > > > > > thats what i try to say and i have obeyd yimura but still
> > > > > 
> > > > > 
> > > > > ![image](https://private-user-images.githubusercontent.com/100792176/348838020-9d781154-0ee7-4594-8475-17a6384c8caf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzM5MTgsIm5iZiI6MTcyMTA3MzYxOCwicGF0aCI6Ii8xMDA3OTIxNzYvMzQ4ODM4MDIwLTlkNzgxMTU0LTBlZTctNDU5NC04NDc1LTE3YTYzODRjOGNhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQyMDAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTE3MjhhMGUzZmJjMTFiMDFkYjI3NDA1NmU2Nzk5YjhiYTY5YzFlYzAzMzQ2MmMxMjFlYWIyNzZiNzhiMGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-OiFkpRvnPCmjS88luKVIwtfO34V1hwQA81DDa0FA_Q)
> > > > > You still don't have my permission to use Casino Pacino which you are still using in your script:
> > > > > ![image](https://private-user-images.githubusercontent.com/100792176/348838391-607de988-f62a-4ac3-8bf6-1c9532b3f48a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzM5MTgsIm5iZiI6MTcyMTA3MzYxOCwicGF0aCI6Ii8xMDA3OTIxNzYvMzQ4ODM4MzkxLTYwN2RlOTg4LWY2MmEtNGFjMy04YmY2LTFjOTUzMmIzZjQ4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQyMDAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODIwODA5ZTc2M2MyYWNhZGE4NGVkMzE0NTY4MWIwYzRjYjA1NzEwYjAzMTYzOGFmODRjMTZkZTFmNGJlMDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qY4-HYvMaWWkZ6_BoYuphTOPh6upngA8R964pZaFv5M)
> > > > > IDK, code looks exactly the same to me, you fucking idiot.
> > > > 
> > > > 
> > > > i removed the uselss codes only the wheel only is in you fucking brainrotted kid
> > > 
> > > 
> > > 4 days left, remove the entire Casino script or get purged from the repo. Tick tock.
> > 
> > 
> > tick tok i wont do it now then i will do more aggressive actions
> 
> NOT MORE AGGRESSIVE ACTIONS! I'M SO SCARED! What's he gonna do? Steal more code? WOW!

LMAO XDDDDDDDDDDDDDDDDDD no

**Comment by L7NEG** [comment]
YOU THINK YOU ARE FUNNY MAN OK NP
